index:
    path: /
    controller: App\Controller\HomeController::index
registration:
    path: register
    controller: App\Controller\RestrationController::index
security:
    path: login
    controller: App\Controller\SecurityController::index
quizz:
    path: quizz
    controller: App\Controller\QuizzController::index
parents:
    path: page_parents
    controller: App\Controller\HomeController::index
cgu:
    path: cgu
    controller: App\Controller\HomeController::cgu
user:
    path: user
    controller: App\Controller\UserController::index


